# Welcome to Jekyll!

title: Jay Cohen | Freelance Native App Developer
email: talk@jcohen.uk
description: Freelance App Developer UK for iOS, Mac OS, Android. 11 years experience with global brands, not for profit and health.
url: "https://jcohen.uk"
lang: en
github_username: jay-cohen
google_analytics: UA-140849878-2

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
date_format: "%b %-d, %Y"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-giphy
  - jekyll-youtube
  - jekyll-sitemap
  - jekyll-coffeescript

sass:
    sass_dir: assets/css
    style: compressed