# Welcome to Jekyll!

title: App Developer and Hybrid to Native Mobile Consultant
email: talk@jcohen.uk
description: Mobile App Developer and hybrid to native consultant. 11 years development experience with brands, not for profit and health. Contact for a free consultation.
url: https://appdeveloperjay.com
lang: en
github_username: jay-cohen
google_analytics: UA-140849878-2

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
date_format: "%b %-d, %Y"
# paginate: 2
# paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-giphy
  - jekyll-youtube
  - jekyll-sitemap
  - jekyll-coffeescript

sass:
    sass_dir: assets/css
    style: compressed

kramdown:
  smart_quotes: apos,apos,quot,quot