# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Freelance App Developer, Apple iPhone, iPad, Apple Watch, Apple TV Developer.
email: talk@jcohen.uk
description: Freelance App Developer for iOS, Mac OS, Apple TV Uk. 12 years experience with international brands, not for profit, and sports apparel.
baseurl: ""
url: "https://jcohen.uk"
lang: en
github_username: jay-cohen
google_analytics: UA-48954482-1


# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
date_format: "%b %-d, %Y"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-giphy
  - jekyll-youtube
  - jekyll-sitemap
  - jekyll-coffeescript

sass:
    sass_dir: assets/css
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
