# Welcome to Jekyll!

title: I'll Fix Your Bug-Ridden App
email: talk@jcohen.uk
description: Freelance iOS App Fixer. I specialise in fixing bug-ridden apps which stops 1 star customer reviews. 11 years development experience with global brands, not for profit and health. Contact for a free consultation.
url: "https://jcohen.uk"
lang: en
github_username: jay-cohen
google_analytics: UA-140849878-2

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
date_format: "%b %-d, %Y"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-giphy
  - jekyll-youtube
  - jekyll-sitemap
  - jekyll-coffeescript

sass:
    sass_dir: assets/css
    style: compressed